version: '3.9'

services:
  crm_back_end:
    build: 
      context: .
      dockerfile: Dockerfile
    image: crm_back
    container_name: crm_back_end
    ports:
      - '8080:80'
    volumes:
      - ./:/app/
    depends_on:
      - crm_back_end_db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=crm_back_end_db
      - DB_PORT=3306
      - DB_DATABASE=crm_back_end
      - MYSQL_USER=local_dev
      - MYSQL_PASSWORD=local_dev@password
    networks:
      - crm_back_end
      
  # ONLY FOR DEVELOPMENT PURPOSE
  composer-crm:
    image: composer:latest
    container_name: composer-crm
    volumes:
      - ./X-CRM:/app/
    working_dir: /app/
    entrypoint: [ 'composer' ]

  redis_alpine-crm:
    image: redis:alpine
    container_name: redis_alpine-crm
    restart: unless-stopped
    ports:
      - "6380:6379"

  # ONLY FOR DEVELOPMENT PURPOSE
  npm-crm:
    image: node:current-alpine
    container_name: npm-crm
    volumes:
      - ./X-CRM:/app/
    ports:
      - "3020:3020"
      # - "3001:3001"
      # - "5173:5173"
    working_dir: /app/
    entrypoint: [ 'npm' ]

  crm_back_end_db:
    image: mysql:8.0
    container_name: crm_back_end_db
    volumes:
      - crm_back_end_data:/var/lib/mysql
    restart: always
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=password_root
      - MYSQL_DATABASE=crm_back_end
      - MYSQL_USER=local_dev
      - MYSQL_PASSWORD=local_dev@password
    networks:
      - crm_back_end

  crm_back_end_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: crm_back_end_phpmyadmin
    restart: always
    ports:
      - "8001:80"
    depends_on:
      - crm_back_end_db
    environment:
      - PMA_HOST=crm_back_end_db
      - MYSQL_ROOT_PASSWORD=password_root
    networks:
      - crm_back_end


volumes:
  crm_back_end_data:

networks:
  crm_back_end:
    driver: bridge